### ISSUE TITLE
Bug in DistributedHashTable.java?

### ISSUE THREAD

**Issue by Menooker** [tomp2p/TomP2P#106]
I found that even I set the EvaluationScheme in the GetBuilder, the get() method would always use VotingSchemeDHT. So I followed to here,in get() method of DistributedHashTable.

       final FutureGet futureDHT = new FutureGet(builder, builder.requestP2PConfiguration()
                .minimumResults(), new VotingSchemeDHT());

This line just ignores the EvaluationScheme in the builder

**Comment by tbocek** [comment]
Thanks for the report! Its now fixed
