### ISSUE TITLE
Protocol specification for iOS

### ISSUE THREAD

**Issue by virl** [tomp2p/TomP2P#137]
I'm planning to use TomP2P with iOS clients.

Is there protocol specification so I will be able to implement iOS client for TomP2P?

**Comment by tbocek** [comment]
There is currently no protocol specification in a separate document, just the code and its comments, e.g. the protocol header spec is here: https://github.com/tomp2p/TomP2P/blob/master/core/src/main/java/net/tomp2p/message/MessageHeaderCodec.java
