### ISSUE TITLE
Your contacts and my questions about this library. I'm making p2p messenger on Android on top of TomP2P

### ISSUE THREAD

**Issue by ChronosX88** [tomp2p/TomP2P#146]
Hello, I almost completely studied your library, and I have questions. Since I am doing a decentralized messenger on Android using TomP2P, I had to do a lot of crutches. I saw that you made a commit 4 days ago. Do you have other contacts besides email (to which you do not reply)?

**Comment by ChronosX88** [comment]
My messenger (I actively developing it): https://github.com/ChronosX88/Influence-android

**Comment by ChronosX88** [comment]
I can help you with your library.

**Comment by tbocek** [comment]
@ChronosX88 Awesome! I just sent you the slack link
