### ISSUE TITLE
net.tomp2p.tracker.TestTracker#testTracker(): ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by exercitussolus** [tomp2p/TomP2P#82]
in line: 

            FutureTracker ft = nodes[300].addTracker(trackerID).domainKey(Number160.createHash("test"))
                    .routingConfiguration(rc).trackerConfiguration(tc).start();

Test run automatically through NetBeans 8.0.2 with JDK 8 on Windows 7. All other tests in this class passed.

**Comment by exercitussolus** [comment]
Runing the same test through command-line Maven invocation ( mvn -Dtest=net.tomp2p.tracker.TestTracker test ) on Windows 7 reproduces the problem. On Linux ( Ubuntu Server 14.04 LTS ) the problem is not reproducible.

**Comment by tbocek** [comment]
Hmm, interesting, I just tried with Win7 and JDK 1.8.0_25 and the test runs. Can you printout ft.failedReason()?

**Comment by exercitussolus** [comment]
This is the test's output immediately before failing: 

( .... )
found on DHT2: 0xc98dc3bb6ebd86a4604f9b31a6e0f88bd0f746f8
found on DHT2: 0x23467b09c6a87649b1c0c0a8af8d62a9d88b4633
found on DHT2: 0xc26295985260a9932f2c2d7b0c069c16b3e5c713
not found: 0x6d8b56f9c9fcc86b16db7bc9636d756af975d719 out of 301
not found: 0xcda17729c0d140c569f4ac2fa68e6a6ac87737ba out of 301
not found: 0x778901f23b2f5070a80446599f76fd337b5ae25b out of 301
not found: 0x5d848a758af537dbaed642672889a60b16f6c7fa out of 301
not found: 0x95f4875337503fb1fda3afc6f711530f9022be14 out of 301
not found: 0x208a622ae98f421333c6a9981b9cbb04c57d3e8a out of 301
not found: 0xa58beb5829256f5a447293415f48ea065a5c1bf7 out of 301
not found: 7
10:04:47.375 [pool-13-thread-1] WARN  net.tomp2p.connection.ChannelServer - cannot bind broadcast UDP /127.255.255.255:4001
10:04:47.375 [pool-13-thread-1] WARN  net.tomp2p.connection.ChannelServer - cannot bind broadcast UDP /192.168.2.255:4001
cancel
10:04:48.045 [pool-15-thread-1] WARN  net.tomp2p.connection.ChannelServer - cannot bind broadcast UDP /127.255.255.255:4001
10:04:48.046 [pool-15-thread-1] WARN  net.tomp2p.connection.ChannelServer - cannot bind broadcast UDP /192.168.2.255:4001
Future (compl/canc):true/false, OK, unknown
cancel
Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 22.095 sec <<< FAILURE!
testTracker(net.tomp2p.tracker.TestTracker)  Time elapsed: 1.393 sec  <<< ERROR!
java.lang.ArrayIndexOutOfBoundsException: 300
( .... ) 

Am I doing something wrong, here on my side ? The test was run on a laptop, with the 192.168.2.7 being a DHCP address obtained from a DHCP router via a cabled switch, i.e. there is no WLAN playing here. Wonder if that is a factor at all ?

**Comment by exercitussolus** [comment]
FAILED REASON :: Future (compl/canc):true/false, OK, unknown

**Comment by tbocek** [comment]
What puzzles me about this error message is the ArrayIndexOutOfBoundsException. This makes in my opinion no sense at all. The array is initialized with 500 peers and its hardcoded.

Do you have in line 28 the following statement?

PeerTracker[] nodes = createNodes(master, 500, rnd);

**Comment by exercitussolus** [comment]
Ooops. My fault. My line 28  reads:


PeerTracker[] nodes = createNodes(master, 50, rnd);

A quick history / diff shows that for some reason, I must have changed the
original 500 into 50, then checked everything into my SVN, which version
Jenkins of course took for its build & test. Changing back to 500 and
re-running the test now yields:

Tests run: 8, Failures: 0, Errors: 0, Skipped: 0

Sorry, my bad. You can close this one. I owe you a beer :-)






*Fortuna audaces adiuvat - hos solos ? *
