### ISSUE TITLE
net.tomp2p.storage.TestStorage.testResponsibility: NullPointerException

### ISSUE THREAD

**Issue by exercitussolus** [tomp2p/TomP2P#83]
in TestStorage.java, line 206:

		Assert.assertEquals(2, storage.findContentForResponsiblePeerID(locationKey).size());

as called from
@Test
	public void testResponsibility() throws Exception

All other tests in TestStorage passed. 

Occurred during a Jenkins build, Maven 3.2.3, JDK 8, on Ubuntu 14.04 LTS; storage was 2 SSDs in RAID-0 config.

**Comment by exercitussolus** [comment]
Possibly a Jenkins problem. Test passes when run from the command line in the Jenkins job's workspace, i.e. with exactly the same configuration, bytecode and storage environment.

**Comment by tbocek** [comment]
In the latest Beta-3, I changed the storage of resposibility. I think this works (no bug anymore) and I'm closing this issue. If the bug is not gone, please reopen.
