### ISSUE TITLE
TestRealNetwork in TomP2P DHT: networking problem

### ISSUE THREAD

**Issue by exercitussolus** [tomp2p/TomP2P#87]
10:41:38.175 [pool-5-thread-1] WARN  net.tomp2p.connection.ChannelServer - cannot bind broadcast UDP /127.255.255.255:4000
10:41:38.176 [pool-5-thread-1] WARN  net.tomp2p.connection.ChannelServer - cannot bind broadcast UDP /192.168.2.255:4000
10:41:38.177 [pool-5-thread-1] WARN  net.tomp2p.connection.ChannelServer - cannot bind broadcast UDP /192.168.1.255:4000
10:41:38.178 [pool-5-thread-1] WARN  net.tomp2p.connection.ChannelServer - cannot bind wildcard broadcast UDP on socket 0.0.0.0/0.0.0.0:4000
10:41:38.179 [pool-5-thread-1] WARN  net.tomp2p.connection.ChannelServer - cannot bind TCP on socket /127.0.0.1:4000
10:41:38.180 [pool-5-thread-1] WARN  net.tomp2p.connection.ChannelServer - cannot bind UDP on socket /127.0.0.1:4000
10:41:38.180 [pool-5-thread-1] WARN  net.tomp2p.connection.ChannelServer - cannot bind TCP on socket /192.168.2.7:4000
10:41:38.181 [pool-5-thread-1] WARN  net.tomp2p.connection.ChannelServer - cannot bind UDP on socket /192.168.2.7:4000
10:41:38.182 [pool-5-thread-1] WARN  net.tomp2p.connection.ChannelServer - cannot bind TCP on socket /192.168.1.3:4000
10:41:38.183 [pool-5-thread-1] WARN  net.tomp2p.connection.ChannelServer - cannot bind UDP on socket /192.168.1.3:4000
no success!

I am at a loss as what can be the cause. The machine has 2 network interfaces, hence the two addressess. Code behaves the same, though,  on servers that have only one NIC and are in only one network.

**Comment by nicoruti** [comment]
The error messages indicate that port 4000 is probably already bound on that machine.

Try also to bind all network interfaces:
```
Bindings bindings = new Bindings().listenAny();
return new PeerBuilder(...).bindings(bindings).start();
```

**Comment by exercitussolus** [comment]
Adding in a Bindings object does take away most of the error messages. I had, however, run a netstat analysis before: most definitely, the 4000 port was and is not bound. What remains are the warnings for the 0.0.0.0 address, both for TCP and UDP: 

[pool-3-thread-1] WARN  net.tomp2p.connection.ChannelServer - cannot bind TCP on socket 0.0.0.0/0.0.0.0:4000
[pool-3-thread-1] WARN  net.tomp2p.connection.ChannelServer - cannot bind UDP on socket 0.0.0.0/0.0.0.0:4000

This still results into a "no success" for the discovery part, although bootstrapping is a success ( and data transfer, with that ). I have another peer on the network on port 4000; it sees the incoming requests, and answers.

**Comment by tbocek** [comment]
What kind of setup are you using for this test? I only can reproduce this problem when I'm already running something on port 4000.

listenAny(); listens to 0.0.0.0 and not to each IP on the interfaces, so thats why so you fewer warninigs. However, this is still the same issue. Just to be sure, can you use a different port than 4000?

**Comment by exercitussolus** [comment]
Repeating the test with ports 22222 and 34567 reproduces the 0.0.0.0
problem.



*Fortuna audaces adiuvat - hos solos ? *

**Comment by tbocek** [comment]
Can you hardcode the ports in each testcase -> startSuperPeer() / startClient()?

I just tried to run  startClient() on Win7 and Linux and its running fine. Could it be that it starts startSuperPeer() and startClient()?

**Comment by exercitussolus** [comment]
Problem solved. I think you just discovered a bug, though, in NetBeans'
wrapper of JUnit testing. Various test methods seem to be started either in
parallel, leading to the 0.0.0.0/[port] binding problem, or otherwise way
too fast after each other.

Forcing individual runs solves the problem.

The guys from netbeans.org prolly owe you a beer.



*Fortuna audaces adiuvat - hos solos ? *

**Comment by tbocek** [comment]
good to know for future issues!

Thanks for investigating
